### ISSUE TITLE
ToDo next entrega

### ISSUE THREAD

**Issue by pacalein** [NoemiCC/DnDMaster#16]
To-Do para próxima entrega:

- [x] [UI] Arregar barra de vida de batalla @aigarrido @NoemiCC 

- [x] [UI + Código] Agregar Tienda y personalización de taberna @pacalein 

- [x] [UI] Mejorar botones y UX general @pacalein 

- [ ] [Código] Incorporar chat en ventana in-game @pacalein 

- [x] [Música] Música @matipina 

- [ ] [UI] Mejorar botones en batalla. Agregar símbolos de jugador y símbolo de turno. @pacalein 

- [ ] [Motor] Ligar personajes seleccionados en la posada con la batalla @NoemiCC 

- [x] [UI] Enchular juegos de runas @pacalein @matipina 

- [x] [UI] Bloquear botones de las habilidades que no se pueden usar. @NoemiCC @aigarrido 

- [x] [Motor] Al iniciar la batalla diga que seleccione un personaje en vez de los botones actuales que dicen "habilidad 1,2 etc" @NoemiCC 

- [ ] [UI] Agregar pantalla completa. @pacalein 

- [x] [Instrucciones] Saltar instrucciones con un botón @matipina 

- [x] [git] dejar juego actual en rama develop @matipina 

- [x] [Build] Arreglar problema plugin de Photon para poder hacer build en WebGL
