### ISSUE TITLE
Entrega Final

### ISSUE THREAD

**Issue by pacalein** [NoemiCC/DnDMaster#22]
**To-Do para última entrega:**

**_Sistema_**
- [x] [Motor] Usar código SaveSystem.cs para llamar a las funciones de guardar y cargar durante el juego.

- [x] [UI] Agregar botón de opciones durante el juego @pacalein 

     - [x] Opción de pantalla completa
 
     - [x] Control de volumen

_**Batalla**_
- [x] [UI] Agregar símbolo de jugador y símbolo de turno. @NoemiCC 

- [x] [UI] Cambiar todos los botones por el nuevo estilo (Assets/Sprites/UI). @pacalein 

- [x] [Motor] Agregar botón para salir de la batalla si el enemigo se desconecta (aborta misión). @NoemiCC 

**_Minijuegos_**
- [x] [UI] Agregar en el fondo de cada minijuego un ícono del personaje que está jugando. @NoemiCC 

- [x] [Motor] Agregar el problema de la rapidez en el juego memorice de las runas.  @aigarrido 

- [x] [Motor] Agregar el problema de dobleclick en las runas en el juego memorice.  @aigarrido 

- [x] [Motor] Verificar: Linkear versión A o B de cada minijuego con el desarrollo de la batalla. @NoemiCC 

- [x] [Motor] Volver a sincronizar notas en el juego del bardo. @matipina 

_**Chat**_

- [ ] [UI] Incorporporar chat en ventana in-game @pacalein 

   - [ ] [UI] Agregar el fondo nuevo de la taberna
 
**_Posada_**
- [ ] [Grafica] Agregar entramado madera.

- [ ] [Motor] Lugar personajes seleccionados en la posada con la batalla

- [x] [Motor] Agregar un collider 2D a cada habitación. @pacalein 

- [x] [Motor] Al dropear al personaje en el collider, hacer la habitación suya y dejarlo en una posición fija. @pacalein 

- [x] [Motor] Sacarle el collider2D a la tabernera shica. @pacalein 

- [x] [Gráfica] Agregar desenfocado cuando habla la tabernera al inicio. @pacalein 

- [ ] [UI/Motor/Gráfica] Agregar instrucciones sobre asignación de habitaciones. @pacalein 

- [ ] [Motor] Para sacar al personaje, tocarlo y que aparezca una cruz. Si se toca, el personaje vuelve a la recepción. @pacalein 

- [x] [UI] Cambiar el icono de cada PJ con una orilla destacada cuando este "on hover". @pacalein 

**_Tienda_**
- [x] [Motor] Que se pueda gastar dinero en la Tienda.

   -  [x] [ Motor] Agregar el resto de los iconos a la tienda. @NoemiCC @pacalein 

   -  [x] [ Motor] Agregar los iconos de las compras a la escena, enlazarlo con trigger de compra.

   -  [x] [ Diseño] Pensar más assets: rack de espadas, plantas, libros @NoemiCC 

   -  [x] [ Diseño] Agregar delimitación amarilla a cada habitación, para agregar el elemento comprado a cada habitación.

   -  [x] [UI] Agregar imagen de botón seleccionado a los botones de categorías de la tienda, para saber qué categoría estas viendo. @pacalein 

**_Música_**
- [ ] [Música/Motor] Agregar la música original a cada escena. @matipina 

- [ ] [Música/Motor] Hacer loop a las canciones para que no parta el intro en cada inicio del tema. @matipina
